// data.jsx — bilingual content + glossary for DDD lesson
// Globals exported at bottom.

const I18N = {
  en: {
    brand: "ArchPath",
    tagline: "DDD field guide",
    start: "Start Learning",
    browseGlossary: "Browse Glossary",
    heroTitle: "Learn DDD, Event Storming & EDA",
    heroSub: "A bite-sized field guide for solution architects. Read between meetings — no slides, no fluff.",
    whatYouLearn: "What you'll learn",
    learningPath: "Learning path",
    modulesN: (n) => `${n} modules`,
    minutes: (n) => `${n} min`,
    start_arrow: "Start →",
    complete: "✓ Complete",
    inProgress: "Continue →",
    sync: "Continue on another device",
    syncExplain: "Your progress lives only in this browser. Export a sync code to pick up on your laptop later.",
    exportCode: "Export sync code",
    pasteCode: "Paste sync code…",
    import: "Import",
    footer1: "Built for architects on the move.",
    footer2: "v0.4 · EN/TH",
    moduleN: (n) => `Module ${n}`,
    readNext: "Next module →",
    retake: "Retake",
    test: "Test your knowledge",
    submit: "Submit answers",
    progressPct: (p) => `${p}% read`,
    scrollHint: "← Scroll to explore →",
    search: "Search 42 terms…",
    noMatch: "No terms match",
    clearFilter: "Clear filter",
    seeExample: "See example",
    hide: "Hide",
    topics: [
      { ico: "DD", cls:"i1", t:"Domain-Driven Design", d:"Model software around the language of the business." },
      { ico: "ES", cls:"i2", t:"Event Storming",       d:"Whiteboard the whole system with sticky notes in hours." },
      { ico: "EDA",cls:"i3", t:"Event-Driven Arch.",   d:"Loosely couple services using events as the contract." },
    ],
    steps: [
      { t:"Discover", d:"Run an Event Storming session to map reality." },
      { t:"Design",   d:"Find bounded contexts and shape the domain model." },
      { t:"Implement",d:"Wire services with events, commands, and queries." },
      { t:"Apply",    d:"Walk through ShopSphere — our case study." },
    ],
  },
  th: {
    brand: "ArchPath",
    tagline: "คู่มือ DDD",
    start: "เริ่มเรียน",
    browseGlossary: "ดูคำศัพท์",
    heroTitle: "เรียน DDD, Event Storming และ EDA",
    heroSub: "คู่มือสั้นๆ สำหรับสถาปนิกซอฟต์แวร์ อ่านระหว่างประชุมได้ — ไม่มีสไลด์ ไม่มีน้ำ",
    whatYouLearn: "สิ่งที่คุณจะได้",
    learningPath: "เส้นทางการเรียน",
    modulesN: (n) => `${n} บทเรียน`,
    minutes: (n) => `${n} นาที`,
    start_arrow: "เริ่ม →",
    complete: "✓ เรียนจบ",
    inProgress: "เรียนต่อ →",
    sync: "เรียนต่อบนเครื่องอื่น",
    syncExplain: "ความคืบหน้าเก็บไว้ในเบราว์เซอร์นี้เท่านั้น ส่งออกโค้ดเพื่อเรียนต่อบนเครื่องอื่น",
    exportCode: "ส่งออกโค้ด",
    pasteCode: "วางโค้ด…",
    import: "นำเข้า",
    footer1: "สร้างเพื่อสถาปนิกที่ไม่หยุดเดิน",
    footer2: "v0.4 · EN/TH",
    moduleN: (n) => `บทที่ ${n}`,
    readNext: "บทต่อไป →",
    retake: "ทำใหม่",
    test: "ทดสอบความเข้าใจ",
    submit: "ส่งคำตอบ",
    progressPct: (p) => `อ่านแล้ว ${p}%`,
    scrollHint: "← เลื่อนเพื่อดูทั้งหมด →",
    search: "ค้น 42 คำศัพท์…",
    noMatch: "ไม่พบคำศัพท์",
    clearFilter: "ล้างตัวกรอง",
    seeExample: "ดูตัวอย่าง",
    hide: "ซ่อน",
    topics: [
      { ico: "DD", cls:"i1", t:"Domain-Driven Design", d:"ออกแบบซอฟต์แวร์ตามภาษาของธุรกิจ" },
      { ico: "ES", cls:"i2", t:"Event Storming",       d:"วาดทั้งระบบด้วยโพสต์อิทในไม่กี่ชั่วโมง" },
      { ico: "EDA",cls:"i3", t:"Event-Driven Arch.",   d:"เชื่อมบริการแบบหลวมโดยใช้ event เป็นสัญญา" },
    ],
    steps: [
      { t:"ค้นหา",    d:"จัด Event Storming เพื่อทำความเข้าใจระบบจริง" },
      { t:"ออกแบบ",   d:"หา Bounded Context และวาดโมเดลโดเมน" },
      { t:"นำไปใช้",  d:"ต่อบริการด้วย event, command, query" },
      { t:"ลงสนาม",   d:"เดินผ่านเคสตัวอย่าง ShopSphere" },
    ],
  },
};

const MODULES = [
  { n:1, en:"Why your domain model matters", th:"ทำไมโดเมนโมเดลถึงสำคัญ",
    mins:6, sub_en:"From CRUD to ubiquitous language.",
    sub_th:"จาก CRUD สู่ภาษาที่ทุกคนใช้ร่วมกัน",
    progress:42, done:false, featured:true },
  { n:2, en:"Bounded Contexts in practice", th:"Bounded Context ในทางปฏิบัติ",
    mins:8, sub_en:"Draw the seams that protect your model.",
    sub_th:"ลากเส้นที่ปกป้องโมเดลของคุณ",
    progress:0, done:false },
  { n:3, en:"Aggregates & invariants", th:"Aggregate และกฎคงที่",
    mins:7, sub_en:"One transaction, one boundary, one root.",
    sub_th:"หนึ่งทรานแซกชัน หนึ่งขอบเขต หนึ่งราก",
    progress:0, done:false },
  { n:4, en:"Event Storming: Big Picture", th:"Event Storming: ภาพรวม",
    mins:9, sub_en:"Run the workshop end-to-end.",
    sub_th:"จัดเวิร์กชอปครบจบในที่เดียว",
    progress:100, done:true },
  { n:5, en:"From sticky notes to services", th:"จากโพสต์อิทสู่บริการ",
    mins:8, sub_en:"Where contexts become deployable units.",
    sub_th:"เมื่อ context กลายเป็นหน่วยที่ deploy ได้",
    progress:0, done:false },
  { n:6, en:"Event-Driven Architecture", th:"สถาปัตยกรรมแบบ Event-Driven",
    mins:10, sub_en:"Choreography, orchestration, and the cost of each.",
    sub_th:"Choreography vs Orchestration และต้นทุนที่ตามมา",
    progress:0, done:false },
  { n:7, en:"Case study: ShopSphere", th:"เคสตัวอย่าง: ShopSphere",
    mins:12, sub_en:"Apply everything to a marketplace platform.",
    sub_th:"ลงมือทำกับแพลตฟอร์มมาร์เก็ตเพลส",
    progress:0, done:false },
];

const GLOSSARY = [
  { id:"ubiquitous-language", cat:"ddd", term_en:"Ubiquitous Language", term_th:"ภาษาที่ใช้ร่วมกัน",
    short_en:"A shared vocabulary used by both engineers and domain experts.",
    short_th:"คำศัพท์ที่ทั้งวิศวกรและผู้เชี่ยวชาญธุรกิจใช้ร่วมกัน",
    full_en:"Ubiquitous Language is the precise, shared vocabulary that domain experts and engineers agree on. It shows up in conversation, on the whiteboard, and directly in code. When the language drifts between the business and the model, bugs and misunderstandings appear at the seams.",
    full_th:"คือคำศัพท์ที่ผู้เชี่ยวชาญธุรกิจและวิศวกรเห็นพ้องกัน ปรากฏทั้งในการสนทนา บนกระดาน และในโค้ดโดยตรง เมื่อภาษาเริ่มไม่ตรงกัน บั๊กและความเข้าใจผิดจะตามมา",
    ex_en:"At ShopSphere, the team renamed 'Order' to 'Cart' before checkout and 'Order' only after payment — code now mirrors how merchants actually talk.",
    ex_th:"ทีม ShopSphere เปลี่ยนชื่อ 'Order' ก่อนชำระเงินเป็น 'Cart' และเรียก 'Order' หลังชำระเงินแล้วเท่านั้น — โค้ดสะท้อนวิธีพูดของผู้ค้าจริง"
  },
  { id:"bounded-context", cat:"ddd", term_en:"Bounded Context", term_th:"Bounded Context",
    short_en:"A boundary within which a particular model is consistent and meaningful.",
    short_th:"ขอบเขตที่โมเดลหนึ่งๆ มีความหมายและสอดคล้องกัน",
    full_en:"A Bounded Context is the explicit boundary inside which a model applies. The same word ('Customer', 'Product') can mean different things in different contexts — that's fine, as long as the seam is explicit. Contexts often map to teams and services.",
    full_th:"ขอบเขตที่ชัดเจนที่โมเดลหนึ่งใช้งาน คำเดียวกัน ('Customer', 'Product') อาจมีความหมายต่างกันในแต่ละ context — โอเคถ้าขอบเขตชัด มักแมปกับทีมและบริการ",
    ex_en:"In ShopSphere, 'Customer' inside Billing carries tax info; 'Customer' inside Catalog only carries display preferences. Same name — different models.",
    ex_th:"ใน ShopSphere 'Customer' ใน Billing มีข้อมูลภาษี ส่วนใน Catalog มีเพียงการตั้งค่าการแสดงผล ชื่อเดียวกัน — โมเดลคนละตัว"
  },
  { id:"aggregate", cat:"ddd", term_en:"Aggregate", term_th:"Aggregate",
    short_en:"A cluster of objects treated as a single unit for data changes.",
    short_th:"กลุ่มของออบเจ็กต์ที่ถือเป็นหนึ่งหน่วยเวลาบันทึก",
    full_en:"An Aggregate groups entities and value objects under a single root. All external mutations go through that root, which enforces invariants. One aggregate, one transaction — that's the rule of thumb.",
    full_th:"กลุ่มของ entity และ value object ภายใต้รากเดียว การเปลี่ยนแปลงจากภายนอกผ่านรากนี้เพื่อรักษากฎ คงที่ หลักนิ้วโป้ง: หนึ่ง aggregate หนึ่งทรานแซกชัน",
    ex_en:"In ShopSphere, the Cart aggregate guards 'total never exceeds wallet credit + payment hold' before any line item is added.",
    ex_th:"ใน ShopSphere, Cart aggregate รักษากฎ 'ยอดรวมห้ามเกินเครดิตกระเป๋า + ยอด hold' ก่อนเพิ่ม item"
  },
  { id:"domain-event", cat:"eda", term_en:"Domain Event", term_th:"Domain Event",
    short_en:"A fact about something that happened in the domain.",
    short_th:"ข้อเท็จจริงเกี่ยวกับสิ่งที่เกิดขึ้นในโดเมน",
    full_en:"A Domain Event records that something meaningful happened — past tense, immutable, named in the business's language. Other contexts react to it without the producer caring who.",
    full_th:"บันทึกว่าสิ่งสำคัญได้เกิดขึ้นแล้ว — อดีต ห้ามแก้ ตั้งชื่อด้วยภาษาธุรกิจ บริการอื่นสามารถตอบสนองได้โดยผู้ผลิตไม่ต้องรู้ว่าใครฟัง",
    ex_en:"OrderPlaced fires from the Cart context. Inventory reserves stock, Loyalty awards points, Email queues a receipt — none of them know about each other.",
    ex_th:"OrderPlaced ออกจาก context Cart, Inventory จองสินค้า, Loyalty ให้พอยต์, Email คิวอีเมลใบเสร็จ — ทั้งหมดไม่ต้องรู้จักกัน"
  },
  { id:"command", cat:"eda", term_en:"Command", term_th:"Command",
    short_en:"A request to do something — may be rejected.",
    short_th:"คำสั่งให้ทำบางอย่าง — ปฏิเสธได้",
    full_en:"A Command is an intent: 'please place this order'. Unlike events, commands are imperative and addressable, and the recipient can reject them if invariants fail.",
    full_th:"คือเจตนา เช่น 'กรุณาวางคำสั่งซื้อนี้' ต่างจาก event ตรงที่เป็นคำสั่ง ระบุปลายทาง และผู้รับสามารถปฏิเสธได้ถ้ากฎไม่ผ่าน",
    ex_en:"PlaceOrder(cartId, paymentRef) targets the Cart aggregate; it rejects with 'PaymentExpired' if the hold lapsed.",
    ex_th:"PlaceOrder(cartId, paymentRef) ส่งถึง Cart aggregate; ปฏิเสธด้วย 'PaymentExpired' ถ้าการ hold หมดอายุ"
  },
  { id:"event-storming", cat:"es", term_en:"Event Storming", term_th:"Event Storming",
    short_en:"A collaborative workshop technique for exploring complex domains.",
    short_th:"เทคนิคเวิร์กชอปแบบมีส่วนร่วมเพื่อสำรวจโดเมนที่ซับซ้อน",
    full_en:"Event Storming is a lightweight, sticky-note-driven workshop. Domain experts and developers map events on a timeline, then layer commands, actors, policies, and hotspots until the system reveals itself.",
    full_th:"เวิร์กชอปแบบเบาๆ ที่ใช้โพสต์อิท ผู้เชี่ยวชาญและนักพัฒนาวาง event บนไทม์ไลน์ จากนั้นเพิ่ม command, actor, policy, hotspot จนระบบเผยตัว",
    ex_en:"ShopSphere kicked off with a 3-hour Big Picture storm: 84 orange notes pinned end-to-end revealed 6 likely bounded contexts before lunch.",
    ex_th:"ShopSphere เริ่มด้วย Big Picture 3 ชั่วโมง: โพสต์อิทส้ม 84 แผ่นเรียงต่อกันเผยให้เห็น 6 bounded context ที่เป็นไปได้ภายในมื้อกลางวัน"
  },
  { id:"hotspot", cat:"es", term_en:"Hotspot", term_th:"Hotspot",
    short_en:"A pink note marking a question, risk, or conflict in the model.",
    short_th:"โพสต์อิทสีชมพูที่ระบุคำถาม ความเสี่ยง หรือข้อขัดแย้ง",
    full_en:"Hotspots are unresolved questions, risks, or arguments uncovered during an Event Storming session. They're not blockers; they're signposts that point to the conversations the team still needs to have.",
    full_th:"คำถาม ความเสี่ยง หรือข้อโต้แย้งที่ยังไม่คลี่คลายจากเซสชัน Event Storming ไม่ใช่ปัญหา แต่เป็นเครื่องหมายว่าทีมยังต้องคุยอะไรเพิ่ม",
    ex_en:"A hotspot at OrderPlaced: 'Do we charge before or after stock check?' ended up reshaping the saga entirely.",
    ex_th:"Hotspot ตรง OrderPlaced: 'เก็บเงินก่อนหรือหลังเช็คสต็อก?' ลงเอยด้วยการเปลี่ยน saga ทั้งชุด"
  },
  { id:"saga", cat:"eda", term_en:"Saga", term_th:"Saga",
    short_en:"A long-running process that coordinates work across multiple services.",
    short_th:"กระบวนการระยะยาวที่ประสานงานหลายบริการ",
    full_en:"A Saga coordinates a sequence of local transactions across services. When a step fails, it triggers compensating actions to roll the world back to a consistent state. Sagas come in two flavors: choreography (event-driven) or orchestration (a central coordinator).",
    full_th:"ประสานงานชุดทรานแซกชันท้องถิ่นข้ามบริการ เมื่อขั้นใดล้มเหลว จะเรียก compensating action เพื่อย้อนกลับ Saga มีสองแบบ: choreography (ขับด้วย event) และ orchestration (มีตัวประสานกลาง)",
    ex_en:"ShopSphere's checkout saga: ReserveStock → ChargePayment → ConfirmOrder. If payment fails, ReleaseStock compensates the first step.",
    ex_th:"Saga checkout ของ ShopSphere: ReserveStock → ChargePayment → ConfirmOrder ถ้าจ่ายเงินล้มเหลว ReleaseStock จะชดเชยขั้นแรก"
  },
  { id:"read-model", cat:"eda", term_en:"Read Model", term_th:"Read Model",
    short_en:"A projection optimized for querying — built from events.",
    short_th:"การฉายข้อมูลที่ปรับให้เหมาะกับการอ่าน สร้างจาก event",
    full_en:"A Read Model is a denormalized view derived from events, tailored to a specific query. Reads stay fast and the write side stays small. Multiple read models can coexist — each for a different question.",
    full_th:"มุมมองข้อมูลแบบ denormalize ที่สร้างจาก event ปรับให้เหมาะกับ query หนึ่งๆ การอ่านเร็วและฝั่งเขียนเล็กลง ใน 1 ระบบสามารถมีหลาย read model ได้",
    ex_en:"ShopSphere keeps a 'SellerDashboard' read model fed by OrderPlaced + Refunded events — the seller's homepage queries one row.",
    ex_th:"ShopSphere เก็บ read model 'SellerDashboard' ที่ป้อนด้วย OrderPlaced + Refunded — หน้าผู้ขายอ่านเพียงแถวเดียว"
  },
  { id:"policy", cat:"es", term_en:"Policy", term_th:"Policy",
    short_en:"A rule that reacts to an event by issuing a command.",
    short_th:"กฎที่ตอบสนอง event ด้วยการออก command",
    full_en:"In Event Storming, a Policy is the 'whenever X, then Y' rule — purple sticky note. It links events to the commands they trigger, capturing reactive business logic that often hides in code.",
    full_th:"ใน Event Storming คือกฎ 'เมื่อใดก็ตามที่ X ให้ Y' (โพสต์อิทสีม่วง) เชื่อม event กับ command ที่ตามมา สะท้อนกฎทางธุรกิจเชิงตอบสนองที่มักซ่อนในโค้ด",
    ex_en:"Policy: 'Whenever PaymentFailed, retry up to 3 times then issue CancelOrder.'",
    ex_th:"Policy: 'เมื่อ PaymentFailed ให้ลองใหม่สูงสุด 3 ครั้ง แล้วออก CancelOrder'"
  },
  { id:"context-map", cat:"ddd", term_en:"Context Map", term_th:"แผนผัง Context",
    short_en:"A bird's-eye view of how bounded contexts integrate.",
    short_th:"มุมมองภาพรวมว่า bounded context เชื่อมโยงกันอย่างไร",
    full_en:"A Context Map shows every bounded context in a system and the relationships between them — partnership, customer/supplier, anti-corruption layer, conformist, and more. It's the org chart for your domain.",
    full_th:"แผนผังที่แสดงทุก bounded context ในระบบและความสัมพันธ์ระหว่างกัน — partnership, customer/supplier, anti-corruption layer ฯลฯ คือผังองค์กรของโดเมน",
    ex_en:"ShopSphere's map: Catalog is upstream supplier to Search; Billing uses an Anti-Corruption Layer to talk to the legacy ERP.",
    ex_th:"แผนผังของ ShopSphere: Catalog เป็น supplier ของ Search; Billing ใช้ Anti-Corruption Layer คุยกับ ERP เดิม"
  },
  { id:"cqrs", cat:"eda", term_en:"CQRS", term_th:"CQRS",
    short_en:"Separate the model that writes from the model that reads.",
    short_th:"แยกโมเดลฝั่งเขียนกับฝั่งอ่านออกจากกัน",
    full_en:"Command Query Responsibility Segregation splits the write model (commands, aggregates) from the read model (projections, views). The two scale independently — and each can use the storage it needs.",
    full_th:"แยกโมเดลฝั่งเขียน (command, aggregate) ออกจากฝั่งอ่าน (projection, view) สองฝั่งสเกลอิสระ และเลือก storage ที่เหมาะสมแยกกันได้",
    ex_en:"ShopSphere writes orders to Postgres but serves seller dashboards from a denormalized Elasticsearch projection.",
    ex_th:"ShopSphere เขียน order ลง Postgres แต่ให้บริการ dashboard ผู้ขายจาก projection ใน Elasticsearch"
  },
];

Object.assign(window, { I18N, MODULES, GLOSSARY });
